<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-27T17:24:29 IST" name="Default suite" finished-at="2023-06-27T17:24:53 IST" duration-ms="23757">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner.Run@673fdbce]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2023-06-27T17:24:29 IST" name="Default test" finished-at="2023-06-27T17:24:53 IST" duration-ms="23757">
      <class name="TestRunner.Run">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:TestRunner.Run@673fdbce]" started-at="2023-06-27T17:24:29 IST" name="setUpClass" finished-at="2023-06-27T17:24:31 IST" duration-ms="1213" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@14d25b6e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner.Run@673fdbce]" started-at="2023-06-27T17:24:31 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-06-27T17:24:53 IST" duration-ms="22305" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Add New Customer"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Customers"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at StepDefination.StepDef.user_can_view_confirmation_message(StepDef.java:162)
at âœ½.User can view confirmation message "The new customer has been added successfully."(file:///F:/Projects/my%20projects/BDDFramework-master/BDDFramework-master/./Features/Customer.feature:19)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:TestRunner.Run@673fdbce]" started-at="2023-06-27T17:24:53 IST" name="tearDownClass" finished-at="2023-06-27T17:24:53 IST" duration-ms="108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- TestRunner.Run -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
